# Generated by Django 4.0.6 on 2022-07-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0018_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='saler',
            field=models.CharField(default='market@admin', max_length=100),
        ),
    ]
