# Generated by Django 4.0.6 on 2022-07-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='dob',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.CharField(choices=[('Montserrado', 'Montserrado'), ('GrandCape Mount', 'GrandCape Mount'), ('Grand Gedeh', 'Grand Gedeh'), ('Lofa', 'Lofa'), ('Gbarpolu', 'Gbarpolu'), ('Bomi', 'Bomi'), ('Rivercess', 'Rivercess'), ('River Gee', 'River Gee'), ('Grand Bassa', 'Grand Bassa'), ('Maryland', 'Maryland'), ('Margibi', 'Margibi'), ('Nimba', 'Nimba'), ('Sinoe', 'Sinoe'), ('Bong', 'Bong'), ('Grand Kru', 'Grand Kru')], max_length=50, null=True),
        ),
    ]
