# Generated by Django 4.0.6 on 2022-07-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userdetail_dob_alter_userdetail_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='landmark',
        ),
    ]
